FROM golang:1.25-alpine

WORKDIR /app

# Install build dependencies & curl to fetch the precompiled Air binary
RUN apk add --no-cache gcc musl-dev git curl

# Install precompiled Air binary to avoid Go compiler/linker issues inside the build stage
RUN curl -sSfL https://raw.githubusercontent.com/air-verse/air/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.61.1

COPY go.mod go.sum ./
RUN go mod download

COPY . .

EXPOSE 8080

CMD ["air", "-c", ".air.toml"]
