FROM golang:1.24-alpine

WORKDIR /app

# Install build dependencies & air for live-reloading
RUN apk add --no-cache gcc musl-dev git
RUN go install github.com/air-verse/air@latest

COPY go.mod go.sum ./
RUN go mod download

COPY . .

EXPOSE 8080

CMD ["air", "-c", ".air.toml"]
